### ISSUE TITLE
Insure use of files in /tmp

### ISSUE THREAD

**Issue by mgeisler** [ryandub/omnibus-ohai-solo#11]
The `install.sh` script writes to a number of files with fixed names in `/tmp`. This opens up the possibility of the old symlink-trick where an attacker symlinks `/tmp/nocheck` to, say, `/etc/passwd`. After writing to `/tmp/nocheck`, the system is left in a bad state since the password file has been overwritten with garbage.

To be secure, a temporary directory needs to be created (securely!) and all files should be written inside it.

**Comment by ryandub** [comment]
This code comes directly from [Chef's upstream install.sh](https://github.com/chef/opscode-omnitruck/blob/master/views/install.sh.erb) and should probably be changed there. In addition, this only applies to Solaris, and since we don't make any packages for Solaris, this can probably just be removed from our `install.sh`.

**Comment by mgeisler** [comment]
Thanks, I agree it should change in the upstream repository then.
